Adds the 'Submit to QuickStatements' button
fnielsen/scholia pull request #1461
Opened 2021-06-19 11:45 UTC by egonw

Implements https://github.com/fnielsen/scholia/issues/1458

2021-06-21 15:14 UTC, Daniel-Mietchen commented
The code looks good, and I just created https://www.wikidata.org/wiki/Q107308161 while testing it.

2021-06-21 15:30 UTC, Daniel-Mietchen commented on scholia/app/templates/404_doi.html
> +               "  <button class=\"btn btn-primary\">Submit to Quickstatements ↗</button>\n" +
```Quickstatements``` should be ```QuickStatements```.

2021-06-21 15:33 UTC, merged

2021-06-21 15:34 UTC, Daniel-Mietchen commented on scholia/app/templates/404_doi.html
>  There was no work found with DOI <a href="https://doi.org/{{ doi }}">{{ doi }}</a>.
I suggest to change this to 
```We found no work in Wikidata with the DOI <a href="https://doi.org/{{ doi }}">{{ doi }}</a>. If you would like to create the item for this work, you can use the <a href="https://www.wikidata.org/wiki/Help:QuickStatements">QuickStatements</a> tool by clicking the "Submit to QuickStatements" button (this requires authentication via <a href="https://www.mediawiki.org/wiki/Help:OAuth">OAuth 2.0</a>).```

2021-06-21 15:35 UTC, Daniel-Mietchen requested changes
Works fine, but presentation could be improved.

2021-06-21 15:52 UTC, egonw commented on scholia/app/templates/404_doi.html
> +               "  <button class=\"btn btn-primary\">Submit to Quickstatements ↗</button>\n" +
Good catch. Sorry I overlooked that.

2021-06-21 15:53 UTC, egonw commented on scholia/app/templates/404_doi.html
>  There was no work found with DOI <a href="https://doi.org/{{ doi }}">{{ doi }}</a>.
Sounds good to me.

2021-06-21 15:55 UTC, fnielsen commented
Is there a need of `urlencode`?

2021-06-21 16:10 UTC, egonw commented
> Is there a need of `urlencode`?

I copied that from the arxiv example and assumed so.

2021-06-22 06:14 UTC, fnielsen commented
arXiv has \d+.\d+ pattern I think. I don't know if that is checked. Can there be '"' in a DOI? '<' and '>' might not be a problem.

2021-06-22 07:01 UTC, egonw commented
I've seen many interesting characters in DOIs. The regex in identifiers.org is `^(doi\:)?\d{2}\.\d{4}.*$`

2021-06-22 13:50 UTC, fnielsen commented
So I suppose we need an urlencoding?

2021-06-22 17:11 UTC, egonw commented
Yes, I think https://github.com/WDscholia/scholia/pull/1461/files#diff-89c1152879b643f0f5eb07072531c16873bb0581597c328b6efa86fddbd72c79R13 should stay.

2021-06-23 07:29 UTC, fnielsen commented
It is line 34 when it is not found.